format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$fill\
$time\
$line_break\
$character"""

[nodejs]
format = "($version )($style)"

[fill]
symbol = " "

[git_branch]
symbol = 'ğŸŒ± '

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨${count}'
behind = 'ğŸ˜°${count}'
diverged = 'ğŸ˜µğŸğŸ’¨${ahead_count}ğŸ˜°${behind_count}'
up_to_date = 'ğŸ’°'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[directory]
style = "bold cyan"
truncation_length = 1
format = "[$path]($style) "


[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"